image: scrapinghub
script:
  - docker build --build-arg DRONE_COMMIT=${DRONE_COMMIT} -t i.scrapinghub.com/$APPNAME-server/$DRONE_BRANCH:${DRONE_COMMIT:0:7} -t i.scrapinghub.com/$APPNAME-server/$DRONE_BRANCH:latest -f Dockerfile.server .
  - docker push i.scrapinghub.com/$APPNAME-server/$DRONE_BRANCH:${DRONE_COMMIT:0:7}
  - docker push i.scrapinghub.com/$APPNAME-server/$DRONE_BRANCH:latest
  - docker build --build-arg DRONE_COMMIT=${DRONE_COMMIT} -t i.scrapinghub.com/$APPNAME-agent/$DRONE_BRANCH:${DRONE_COMMIT:0:7} -t i.scrapinghub.com/$APPNAME-agent/$DRONE_BRANCH:latest -f Dockerfile.agent .
  - docker push i.scrapinghub.com/$APPNAME-agent/$DRONE_BRANCH:${DRONE_COMMIT:0:7}
  - docker push i.scrapinghub.com/$APPNAME-agent/$DRONE_BRANCH:latest
